# render.yaml
services:
  - type: web
    name: flask-form
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    workingDir: src
    plan: free
